### ISSUE TITLE
pod termination might cause dropped connections

### ISSUE THREAD

**Issue by nirnanaaa** [kubernetes-sigs/aws-load-balancer-controller#2366]
**Describe the bug**
When a pod is Terminating it will receive a SIGTERM connection asking it to finish up work and after that it will proceed with deleting the pod. At the same time that the pod starts terminating, the aws-load-balancer-controller will receive the updated object, forcing it to start removing the pod from the target group and to initialize draining. 

Both of these processes - the signal handling at the kubelet level and the removal of the Pods IP from the TG - are decoupled from one another and the SIGTERM might have been handled before or at the same time, that the target in the target group has started draining. 
As result the pod might be unavailable before the target group has even started its own draining process. This might result in dropped connections, as the LB is still trying to send requests to the properly shutdown pod. The LB will in-turn reply with 5xx responses.

**Steps to reproduce**

- Provision an ingress with an ALB attached
  ```yaml
    alb.ingress.kubernetes.io/certificate-arn: xxx
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "10"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=30
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: xxx
    alb.ingress.kubernetes.io/tags: xxx
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=60
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
  ```
- Create a service and pods (multiple ones through a deployment work best) for this ingress
- (add some delay/load to the cluster, that will cause the AWS requests to be slower or have to be retried)
- startup an HTTP benchmark to produce some artificial load
- rollout a change to the deployment or just evict some pods

**Expected outcome**
- The SIGTERM should only start after the ALB has either removed the target from the Target Group or at least doesn't send any new traffic to the pod after it received the SIGTERM signal

**Environment**
- an HTTP service

All our ingresses have 

* AWS Load Balancer controller version `v2.2.4`
* Kubernetes version
  ```
  Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c579e", GitCommit:"8c579edfc914f013ff48b2a2b2c1308fdcacc53f", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
  ```
* Using EKS (**yes**), if so version ? 1.18 eks.8

**Additional Context**:

We've been relying on [Pod-Graceful-Drain](https://github.com/foriequal0/pod-graceful-drain), which unfortunately forks this controller and intercepts and breaks k8s controller internals.

You can achieve a pretty good result as well using a `sleep` as `preStop`, but that's not reliable at all - due to the fact that it's just a guessing game if your traffic will be drained after X seconds - and requires statically linked binaries to be mounted in each container or the existence of sleep in the operating system.

I believe this is not only an issue to this controller, but to k8s in general. So any hints and already existing tickets would be very welcome.

**Comment by M00nF1sh** [comment]
@nirnanaaa 
I'm not aware of any general solution that is better than a preStop hook. Since after all, it's the connection is controlled by both end of application(client/server) instead of LBs.

In my mind, it can be handled in a protocol specific way by client/server if you have control over server's code
e.g. If the server receives a sigTerm, it can
*  continue listen for incoming connections. (only a limited number of new connections will coming since LB will start deregister the target soon)
*  tell the existing long running clients to migrate to use new connections in protocol-specific manner, e.g.:
        * http: `connection: close` header in responses
        * websocket: GOAWAY message.
*  waiting for all existing connection terminate and exit
Once we did above, then you only need to set a large terminationGracePeriodSeconds.

I have a sample app implemented above: https://github.com/M00nF1sh/ReInvent2019CON310R/blob/master/src/server.py#L24

**Comment by nirnanaaa** [comment]
Hey @M00nF1sh thanks for your input. I fear this is exactly what I thought was supposed to fix it. But thinking about it: if the server does all of this: what does prevent the LB from still sending traffic to the target - even for a brief period. Unfortunately We're hitting this exact scenario quite often.

**Comment by ejholmes** [comment]
We also ran into this issue. The preStop hack generally works, but it's still a hack and it still seems to fail to synchronize the "deregistration before SIGTERM" properly. Even with this in place, we've seen intermittent cases where the container still seems to get a SIGTERM before the target is deregistered (possibly by the DeregisterTargets API call getting throttled).

This is a pretty serious issue for anyone trying to do zero-downtime deploys on top of Kubernetes with ALB's.

**Comment by M00nF1sh** [comment]
@nirnanaaa 
I see. The remaining gap is that the pods itself finishes draining too fast before LBs deregister them.

For this case, a sleep is indeed needed since we don't have any information available on when the LBs actually stops sending targets. (even when the targets shows as draining after the controller made the deregisterTargets call, it still takes time for the changes to be actually propagated to ELB's dataplane). 
If ELB have support for server-side retry, it could handle this nicely, but i'm not aware when that will be done.

**Comment by nirnanaaa** [comment]
I was just wondering whether this should be solved at a lower level - that's why I also opened an issue on k/k. This is not something just limited to this controller (although in cluster LBs are less likely to have this issue, it's still present). 


And you're absolutely right. Client side retries would probably solve this. There are even some protocols like GRPC which could work around this problem, but the truth is that we cannot really control what's being run on the cluster itself - hence also my doubt with the usage of sleep.

**Comment by nirnanaaa** [comment]
![shutdown-behavior](https://user-images.githubusercontent.com/1064750/143430091-2d042b5b-9140-4608-9a34-3f82389795f5.jpg)
I've also drawn up a convenient picture detailling the issue further - the big, organge box is where things are happening decoupled from one another.

**Comment by BrianKopp** [comment]
This is indeed a problem that exists in kubernetes generally, not just ALB. We ran into this a lot using classic load balancers in proxy mode to nging ingress with external traffic policy local to get real IPs.

Using the v2 ELBs with ip target groups is a big improvement over the external traffic policy local mechanism requiring health check failures to get the node out of the instance list.

That being said, this still is an issue that can happen. Sleeps and prestop hooks are really the only game in town. I'm not aware of any kind of prestop gate like the readiness gate this controller can inject.

Is there a community binary that does this already OOTB? If not, that'd be a good little project.

Another alternative is to use a reverse proxy like ingress nginx be the target for your alb ingress instead of your application. Then your container lifecycle events for your alb targets will be much, much less frequent.

**Comment by nirnanaaa** [comment]
@BrianKopp we've thought about running a sidecar, which provides a statically linked binary to a common - in mem - volume, that the main container could use as preStop. I just couldn't come up with a generic solution to check for "is this pod still in any target group" - without either running into API throttles (and potentially blocking the main operation of the aws-lb-controller) - or completely breaking single responsibility principles.

**Comment by BrianKopp** [comment]
IIRC, sidecar for this sort of thing is a trap since a prestop hook interrupts the sigterm for *its* container, not all containers. Your http container would get its sigterm immediately. 

I've actually begun thinking about starting a project to address this. My thought is to have an http service inside the cluster, say at `drain-waiter`. And you could call `http://drain-waiter/drain-delay?ingress=your-ingress-name&namespace=your-namespace&max-wait=60`, and then you could have a prestop hook curling that url. We can get the hostname from the ingress object, and therefore filter the target groups very easily.

What do you think? Is this worth making a thing?

**Comment by nirnanaaa** [comment]
Oh I was not talking about processing the sigterm in the sidecar. If you read closely I only spoke about providing the binary ;)

For our use case even a simple HTTP query will not work if not done through some statically linked binary, since we cannot even rely on libc to be present.

**Comment by BrianKopp** [comment]
Ok I see what you were suggesting. I mean, if the requirement is that we cannot place any runtime demands on the http container, then yes we would need some kind of sidecar to be injected to provide some functionality, along with a mutating webhook to add the container and prestop hook, in case a prestop hook wasn't already present. That part seems like a bit of a minefield. 

I was thinking about putting together something that would work for now until such a solution would be possible, if at all possible.

If one didn't want to place any dependency requirements on the main http container (eg curl), a prestop hook could wait for a signal over a shared volume from a lightweight curling sidecar

**Comment by sftim** [comment]
I think this is best addressed by extending the Pod API. Yes, that's not a trivial change. However, the Pod API is what the kubelet pays attention to. If you want the cluster to hold off sending SIGTERM then there needs to be a way in the API to explain why that's happening. _This_ code doesn't have the levers to pull to make things change how we'd need.

Another option is to redefine SIGTERM to mean “get ready to shutdown but keep serving”. I don't think that's a helpful interpretation of SIGTERM though.

**Comment by ejholmes** [comment]
I think that's correct. This is generally what we've used in helm charts:

```yaml
# ingress
alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds={{ .Values.deregistrationDelay }}
# pod
terminationGracePeriodSeconds: {{ add .Values.deregistrationDelay .Values.deregistrationGracePeriod 30 }}
command: ["sleep", "{{ add .Values.deregistrationDelay .Values.deregistrationGracePeriod }}"]
```

Where `deregistrationGracePeriod` provides a buffer for DeregisterTargets getting rate limited.

**Comment by mbyio** [comment]
For NLBs in IP mode (everything should be similar for other LBs and modes):

- deregistration takes at least 2 minutes regardless of the deregistration delay setting
- during deregistration, the pod may still receive new requests/connections even though it is in the process of deregistering
- the `preStop` hook therefore has to sleep for at least 2 minutes
- and the termination grace period has to be 2 minutes + the maximum time for any request to complete + time for any background processes to clean up + a short grace period in case there is a delay (eg. deregistration was rate limited)

**Comment by ejholmes** [comment]
> deregistration takes at least 2 minutes regardless of the deregistration delay setting

That's an interesting finding. Is there some documentation you can point to that highlights this (assuming it's AWS side)?

**Comment by mbyio** [comment]
I believe it is all on AWS' side yes. No I couldn't find any documentation about this. All due respect to AWS engineers, their ELB documentation is horrible, missing a lot of important information. I found this by writing some programs that use raw TCP connections (so I can monitor every aspect) and manually triggering deregistration in various ELB configurations to record the timing. It consistently took 2 minutes.

**Comment by BrianKopp** [comment]
In your testing, did the target group state for the target show the ip as draining while it was receiving packets still? Did it receive packets after the target dropped completely out of the target group? I've got a project I'm working on to add a delay in the prestop hook to wait until the ip is out of the target group. Would that be helpful here?

**Comment by mbyio** [comment]
Yes, it did correctly show the IP on the target list as draining as soon as I requested deregistration. And when it was removed from the target list, it also stopped receiving new connections. So, if a tool was monitoring the target list and used that to delay sending SIGTERM to a pod until the pod is out of the target list (eg. using preStop), that would solve the problem. It would be the opposite of a readiness gate. I think one difficulty is AWS has some restrictive rate limits, so depending on your scale I don't think you can just have every pod hitting the API in the preStop hook.

**Comment by dcarley** [comment]
We were told this by AWS support:

> Similarly, when you deregister a target from your Network Load Balancer, it is expected to take 90-180 seconds to process the requested deregistration, after which it will no longer receive new connections. During this time the Elastic Load Balancing API will report the target in 'draining' state. The target will continue to receive new connections until the deregistration processing has completed. At the end of the configured deregistration delay, the target will not be included in the describe-target-health response for the Target Group, and will return 'unused' with reason 'Target.NotRegistered' when querying for the specific target.

Sleeping for 180s (3m) still hasn't been reliable for us though, so we're currently at 240s (4m) 😭

**Comment by nirnanaaa** [comment]
we've actually started sharding our services across multiple aws accounts/eks clusters, just to lower the number of pending/throttled API requests and to increase the speed at which each controller can operate. 

But then again: the probability of this error happening is still not zero. On a new AMI release we frequently experience dropped packages (even with X seconds of sleep as preStop)

**Comment by mbyio** [comment]
I think the controller should automatically add a preStop hook to pods, which waits until the controller indicates it is safe to start terminating. That would nip this in the bud once and for all.

**Comment by MatthiasWinzeler** [comment]
we wondered that the - according to the comments in this thread - it would take up to minutes for the NLB to stop sending new request, so we reached out to the AWS support. Outcome:

- The issue with taking **minutes** until a target is properly drained apply only to NLB, not ALB (ALB reacts faster)
- The statement was that it can indeed happen that after deregistration the ALB still might send new requests to the target. This should be compensated with a pre stop sleep - they recommended 60 secs to be on the safe side.
- with 60 pre stop secs on the ALB, our load tests did not show any 502 errors during rolling upgrades.

Also we were told that the issue (ALB/NLB sending requests to draining targets) should be fixed in the future, so we expect to eventually be able to decrease the pre stop sleep to a lower number.

**Comment by Indigenuity** [comment]
Can confirm that even after targets are marked as `draining` in an ALB target group, they still receive traffic.  In a test where I sent a constant load to a 2-pod hello-world web server with PodDisruptionBudget minAvailable=1, the timeline I saw was:
- 0 seconds: `kubectl drain`
- 1 second: pod 1 enters `Terminating`, receives SIGTERM
- 2 seconds: target marked as `draining` in target group and Deregistration starts
- 2 seconds: replacement pod 1 enters `ContainerCreating`
- 2-15seconds: traffic sent to ALB receives 504 and 502 responses mixed in with 200
- 4 seconds: pod 1 SIGKILL
- 17 seconds: replacement pod 1 starts and immediately receives traffic, starts returning 200
- 19 seconds: traffic finally stops going to the terminated pod, responses are all 200
- 21 seconds: pod 2 starts following the same timeline as pod 1, receives SIGTERM followed by SIGKILL
- 21-40 seconds: traffic sent to ALB receives 504 and 502 responses mixed in with 200
- 41 seconds: responses once again go back to all 200
- 193 seconds: old pod 1 Deregistration finishes
- 221 seconds: old pod 2 Deregistration finishes

So the ALB continues to send traffic as normal (not even a reduced amount of traffic AFAICT) to a target after it enters the `draining` state, but ceases that traffic before Deregistration completes.  So there's some internal event that we don't get to see.

This is the timeline for requests that take <10ms to process; obviously things are different for longer-lived requests.

**Comment by eric-kinsa** [comment]
That test doesn't account for existing connections that need to finish during the draining process. If a request takes several seconds, (lets say a visual query app) V and is happening during a deployment, the possibility is high that request is going to be killed when the pod its running on is killed instead of letting it cleanly finish.

**Comment by gsusI** [comment]
The same issue happens when using the kind _Service_ of type _Load Balancer_, which generates a Network Load Balancer (NLB)

**Comment by JamieSinn** [comment]
We've also seen this happen as a result of an EC2 Spot based node being killed/taken. The pod gets removed, and the ALB (via ingress) fails to remove the target in time.

**Comment by sftim** [comment]
> We've also seen this happen as a result of an EC2 Spot based node being killed/taken. The pod gets removed, and the ALB (via ingress) fails to remove the target in time.

Is that Pod removal happening due to node problem detector / EC2 node termination handler, whilst the kubelet is still alive?

I'm wondering in particular about what the timeline is for that removal and what finalizers might or might not be set on the Pod during its deletion.

**Comment by JamieSinn** [comment]
> Is that Pod removal happening due to node problem detector / EC2 node termination handler, whilst the kubelet is still alive?

Technically yes- the node is killed because it is marked unhealthy - but the reason it's marked as unhealthy is because AWS is taking the instance back into their pool. `BidEvictedEvent` is the exact message of why this happens - and it triggers a 2 minute warning on the removal of node as a whole - so instances start to shut down, which then (either doesn't at all, or is delayed) doesn't properly cascade from EKS -> ALB. 

Timeline wise - I'll see if i can find some logs and get a timeline - but we seem to have about 5-10s of 502 errors because the target is gone but the ALB doesn't know/hasn't removed it yet.

**Comment by sftim** [comment]
Startup probes allow for a longer (or shorter) startup time before regular _liveness_ probes kick in. If you want to define a probe that must pass before an endpoint is treated as healthy for traffic to come in, define a readiness probe.

Also see https://kubernetes.io/blog/2022/12/30/advancements-in-kubernetes-traffic-engineering/

There are some relevant features that became stable in the v1.26 release, and another that moved to beta.

**Comment by cayla** [comment]
> And another behaviour that I saw which is really strange is that in a rolling update, there is a point where my ALB had one pod in initial state, 2 pods in draining but no pod in Healthy state which shouldn't happen at all. And it seems that the controller also doesn't take into consideration the startupProbe, adding a Pod to the ALB before that is finished.

I also recommend reading up on [pod readiness gates ](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/pod_readiness_gate/)

**Comment by rofreytag** [comment]
>during deregistration, the pod may still receive new requests/connections even though it is in the process of deregistering

I think this is the main culprit. I don't understand how, at-all, the NLB/ALBs would forward new connections to a draining target. I am currently moving from Classic LB to NLB in front of ingress-nginx and in the process was trying  `externalTrafficPolicy: Local` on the ingress-controller service. 

AWS Engineers: I am expecting a load balancer that is "draining" to not forward new connections to a target!

**Comment by mattjamesaus** [comment]
We came across this issue and found ours to be a combination of both the Cluster Autoscaler (CA) and the Load Balancer Controller working in tandem when external traffic policy was set to cluster. We'd have nodes getting ready to be scaled in (being pretty much empty except for kube-proxy) then the CA would kick in and taint the node and terminate it well before it was deregistered by the LB Controller.

This would result in-flight requests being dropped from kube-proxy to another node (that ran our HAPRoxy pods). It appears now tho that the latest CA introduces a `--node-delete-delay-after-taint` which will gracefully wait an amount of seconds before killing the node. I'm about to test this but my assumption here is that if this delay is set to just longer than your deregistration timeout the node will be kept around long enough to be successfully pulled out of the target group and gracefully terminate all the in-flight connections going to kube-proxy.

This would still require adequate pod termination for whatever service gets the traffic but most handle that perfectly well already.

**Comment by mbyio** [comment]
> > I think the controller should automatically add a preStop hook to pods, which waits until the controller indicates it is safe to start terminating. That would nip this in the bud once and for all.
> 
> Doesn't seem to be working though as the pod dies immediately instead of gracefully shutdown, we had to remove the `preStop` hook and sleep 30s instead to make all upstream GRPC errors go away

This automatic preSop hook was a suggestion for what they should implement, it isn't implemented yet.

**Comment by Ghilteras** [comment]
What I'm saying is that there's already a preStop hook that should wait for shutdown and it doesn't do thay

**Comment by mbyiounderdog** [comment]
If you have a preStop hook that waits for shutdown, then it was not added by the controller.

**Comment by Ghilteras** [comment]
when I say wait for the shutdown I just mean a simple `sleep` and sure there are less errors using the sleep `preStop`, but as the OP said it's a hack, there's no way to make the controller gracefully terminate and the OP is also correct in saying that this is not a specific aws-load-balancer controller issue b/c we have exactly the same problem on the nginx ingress controller deployed on bare metal

**Comment by johngmyers** [comment]
I can't think of a good way for LBC to communicate to a `preStop` that the pod has been deregistered. The pod would have to be in a ServiceAccount that has RBAC to watch some resource that LBC would update or there'd have to be some network connection opened up between LBC and the pod.

**Comment by johngmyers** [comment]
@Ghilteras no, the pod knows about long-lived connections, is perfectly capable of closing them itself, and knows when they have gone away. The problem is new connections that keep coming in from the load balancer. The pod does not know when the load balancer has finished deregistering it and thus there will no longer be any more new incoming connections.

**Comment by mbyio** [comment]
> The pod would have to be in a ServiceAccount that has RBAC to watch some resource that LBC would update or there'd have to be some network connection opened up between LBC and the pod.

I'm no longer working at the company where I needed this day-to-day. However, we would have been willing to deal with a lot of setup, including service accounts etc, in order to have an automated fix for this bug. It was a major pain point. As you can see in these comments, it is also hard for many people to understand, and therefore, hard to work around.

**Comment by Ghilteras** [comment]
> @Ghilteras no, the pod knows about long-lived connections, is perfectly capable of closing them itself, and knows when they have gone away. The problem is new connections that keep coming in from the load balancer. The pod does not know when the load balancer has finished deregistering it and thus there will no longer be any more new incoming connections.

How do you close and re-open a GRPC connection from the client to force it to dial another pod? I don't see anything like this in the grpc libraries. If your client gets a GOAWAY all it can do is retry it, which will leverage the existing long lived connection to the Terminating pod, which means it will keep failing. There is no way of automatically handle this from client without wrapping it with custom logic that servers the connection on GOAWAY/draining errors from servers. All this because NGINX cannot close the long lived connection on its side when it's gracefully shutting down? I think I'm missing something here

**Comment by mbyio** [comment]
@Ghilteras You may be looking at the wrong Github issue. This issue is about a case where AWS load balancers can send new requests to terminating pods that have already stopped accepting new requests. NGINX is not involved.

**Comment by johngmyers** [comment]
@Ghilteras I'm saying the terminating server pod is capable of shutting down the long-lived connection.

**Comment by Ghilteras** [comment]
> @Ghilteras I'm saying the terminating server pod is capable of shutting down the long-lived connection.

I don't see any way for this ingress controller (or others, as OP said this is not a specific issue of this controller) to be capable of shutting down long-lived connections, if you are aware of a way of doing this please share.

**Comment by johngmyers** [comment]
I wasn't talking about this ingress controller shutting down the connection.

**Comment by Ghilteras** [comment]
the GRPC server is already sending GOAWAYs, the issue is that when the clients reconnect they just end up going back to the Terminating pod, which should not be getting _new_ traffic through the ingress, but it does and that's when we see the server throwing hundreds of `connection reset by peer` errors

**Comment by johngmyers** [comment]
@Ghilteras and thus the problem is with new connections coming in from the load balancer, as I previously stated.

**Comment by Roberdvs** [comment]
For anyone still struggling with the interaction between NLB and ingress-nginx-controller, this is the setup that seems to better mitigate the issues for us for HTTP traffic.

ingress-nginx chart values snippet:

```
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: "deregistration_delay.timeout_seconds=0"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: 2
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: 5

# Mantain existing number of replicas at all times
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
# Add a pause to make time for the pod to be registered in the AWS NLB target group before proceeding with the next
# https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1834#issuecomment-781530724
# https://alexklibisz.com/2021/07/20/speed-limits-for-rolling-restarts-in-kubernetes#round-3-set-minreadyseconds-maxunavailable-to-0-and-maxsurge-to-1
minReadySeconds: 180
# Add sleep on preStop to allow for graceful shutdown with AWS NLB
# https://github.com/kubernetes/ingress-nginx/issues/6928
# https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2366#issuecomment-1118312709
lifecycle:
  preStop:
    exec:
      command: ["/bin/sh", "-c", "sleep 240; /wait-shutdown"]
# -- Maximum unavailable pods set in PodDisruptionBudget.
maxUnavailable: 1
```

Also, `externalTrafficPolicy` on the service of type LoadBalancer is set to `Cluster`.

With this setup rolling updates are reliable enough albeit reaaally slow, mostly due to having to account for https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1834#issuecomment-781530724

Hope it helps someone, and if any detects any issues or improvements, it would be good to know.

Other issues referenced:
- https://github.com/kubernetes/ingress-nginx/issues/6928
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2131

**Comment by venkatamutyala** [comment]
Thanks @Roberdvs this is huge. I just came across the problem in my cluster while testing an upgrade and I was able to fix it within an hour by referencing your work. I have been running statuscake.com with 30sec checks to help verify your fix works as expected. Prior to the change I had a minute or two of downtime. After the change, I appear to be at a real 100% uptime. For anyone else coming across this, I implemented the following I am using the default NLB deployment method given I don't have AWS LB Controller installed.

```yaml
        controller:
          service:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            type: "LoadBalancer"
            externalTrafficPolicy: "Local"
          # https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2366
          # https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2366#issuecomment-1788923154
          updateStrategy:
            rollingUpdate:
              maxSurge: 1
              maxUnavailable: 0
          # Add a pause to make time for the pod to be registered in the AWS NLB target group before proceeding with the next
          # https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1834#issuecomment-781530724
          # https://alexklibisz.com/2021/07/20/speed-limits-for-rolling-restarts-in-kubernetes#round-3-set-minreadyseconds-maxunavailable-to-0-and-maxsurge-to-1
          minReadySeconds: 180
          # Add sleep on preStop to allow for graceful shutdown with AWS NLB
          # https://github.com/kubernetes/ingress-nginx/issues/6928
          # https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2366#issuecomment-1118312709
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 240; /wait-shutdown"]
```

chart repo: https://kubernetes.github.io/ingress-nginx'
name: ingress-nginx
chart version: v4.8.3

**Comment by michaelsaah** [comment]
was thinking about this again... has anyone thought about modifying the ALB controller to set a finalizer on the pods with in the TG, and using that as a hook to prevent termination until it's been successfully removed from the TG? this would hinge on the SIGTERM not getting sent until after all finalizers have been removed, which I would expect to be true but would need to verify.

**Comment by ibalat** [comment]
any update? I have same problem and I think taht it can be related also autoscaler. Please can you view it: https://github.com/kubernetes/autoscaler/issues/6679

**Comment by Roberdvs** [comment]
> For anyone still struggling with the interaction between NLB and ingress-nginx-controller, this is the setup that seems to better mitigate the issues for us for HTTP traffic.
> 
> ingress-nginx chart values snippet:
> 
> ```
> service:
>   annotations:
>     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
>     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
>     service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
>     service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
>     service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: "deregistration_delay.timeout_seconds=0"
>     service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: 2
>     service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: 5
> 
> # Mantain existing number of replicas at all times
> updateStrategy:
>   type: RollingUpdate
>   rollingUpdate:
>     maxSurge: 1
>     maxUnavailable: 0
> # Add a pause to make time for the pod to be registered in the AWS NLB target group before proceeding with the next
> # https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1834#issuecomment-781530724
> # https://alexklibisz.com/2021/07/20/speed-limits-for-rolling-restarts-in-kubernetes#round-3-set-minreadyseconds-maxunavailable-to-0-and-maxsurge-to-1
> minReadySeconds: 180
> # Add sleep on preStop to allow for graceful shutdown with AWS NLB
> # https://github.com/kubernetes/ingress-nginx/issues/6928
> # https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2366#issuecomment-1118312709
> lifecycle:
>   preStop:
>     exec:
>       command: ["/bin/sh", "-c", "sleep 240; /wait-shutdown"]
> # -- Maximum unavailable pods set in PodDisruptionBudget.
> maxUnavailable: 1
> ```
> 
> Also, `externalTrafficPolicy` on the service of type LoadBalancer is set to `Cluster`.
> 
> With this setup rolling updates are reliable enough albeit reaaally slow, mostly due to having to account for [#1834 (comment)](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1834#issuecomment-781530724)
> 
> Hope it helps someone, and if anyone detects any issues, improvements, or recommendations, it would be good to know.
> 
> P.S: have yet to play around with [pod readiness gates](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/pod_readiness_gate/)
> 
> Other issues referenced:
> 
>     * [Zero downtime upgrade kubernetes/ingress-nginx#6928](https://github.com/kubernetes/ingress-nginx/issues/6928)
> 
>     * [Document zero-downtime deployment for IP targets #2131](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2131)

According to https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1834#issuecomment-2359354913 NLBs have had improvements to the target registration behind-the-scenes so the `minReadySeconds` time can probably be reduced now to make rollouts faster.

**Comment by msvticket** [comment]
> was thinking about this again... has anyone thought about modifying the ALB controller to set a finalizer on the pods within the TG, and using that as a hook to prevent termination until it's been successfully removed from the TG? this would hinge on the SIGTERM not getting sent until after all finalizers have been removed, which I would expect to be true but would need to verify.

I tried to find information about this and the clearest statement about this I found in kubernetes/kubernetes#73584. This issue was closed with the comment: 

> This is working as designed. Finalizers block deletion of the pod API object, not termination of the containers. You can use graceperiodseconds and prestophooks to give your containers time to shut down gracefully on termination.

**Comment by sftim** [comment]
I think ideally we look to enrich [Gateway](https://gateway-api.sigs.k8s.io/) with feature here. The Service and Pod APIs are stable and making changes there is more costly; Gateway (or perhaps a new supporting API within the overall gateway family) has a flexibility to help us adapt.

**Comment by youwalther65** [comment]
For NLB target registration see my comment [here](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1834#issuecomment-2359354913).
I wouldsuggest to  leave deployment [minReadySeconds](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#min-ready-seconds) at the default value of 0 and use the more robust approach of [pod readiness gate](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.8/deploy/pod_readiness_gate/) instead.
Even though target registration is much faster now, other things like ELB API throttling can make registration and healthiness slower (imagine you are running AWS Lb Ctlr with a couple of load balancers, dozens of target groups  and each target group has lots of targets and ELB v2 API calls get throttled an AWS Lb Ctlr does backoff and retry). So relying on "pod readiness" is safe because it will "sync" with the ALB/NLB.

**Comment by zac-nixon** [comment]
Kubernetes 1.32 now natively supports sleep as preStop action, meaning that you do not have to use `exec sleep ...` anymore.

https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/3960-pod-lifecycle-sleep-action/README.md

I am in the process of writing a KEP that should remove using arbitrary sleeps in order to perform pod synchronization.

**Comment by youwalther65** [comment]
> Kubernetes 1.32 now natively supports sleep as preStop action, meaning that you do not have to use `exec sleep ...` anymore.
> 
> https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/3960-pod-lifecycle-sleep-action/README.md
> 
> I am in the process of writing a KEP that should remove using arbitrary sleeps in order to perform pod synchronization.

Sounds great. Slight addition: preStop sleep action is already supported and enabled by default as Beta in 1.30, though 1.32 adds adding a 0s preStop hook as an Alpha feature, see [here](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#:~:text=PodLifecycleSleepAction)

**Comment by techdragon** [comment]
The underlying issue is not resolved.
/reopen

**Comment by nirnanaaa** [comment]
Here you go @techdragon 
/reopen
